language: php
dist: trusty
sudo: false
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

install:
  - composer update
script:
  - php vendor/bin/phpunit tests --coverage-clover=coverage.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)
